export type Book = { id: string; name: string; chapters: number; file: string };

export const BOOKS: Book[] = [
  { id: "genesis", name: "Genesis", chapters: 50, file: "Genesis.json" },
  { id: "exodus", name: "Exodus", chapters: 40, file: "Exodus.json" },
  { id: "leviticus", name: "Leviticus", chapters: 27, file: "Leviticus.json" },
  { id: "numbers", name: "Numbers", chapters: 36, file: "Numbers.json" },
  { id: "deuteronomy", name: "Deuteronomy", chapters: 34, file: "Deuteronomy.json" },
  { id: "joshua", name: "Joshua", chapters: 24, file: "Joshua.json" },
  { id: "judges", name: "Judges", chapters: 21, file: "Judges.json" },
  { id: "ruth", name: "Ruth", chapters: 4, file: "Ruth.json" },
  { id: "1-samuel", name: "1 Samuel", chapters: 31, file: "1-Samuel.json" },
  { id: "2-samuel", name: "2 Samuel", chapters: 24, file: "2-Samuel.json" },
  { id: "1-kings", name: "1 Kings", chapters: 22, file: "1-Kings.json" },
  { id: "2-kings", name: "2 Kings", chapters: 25, file: "2-Kings.json" },
  { id: "1-chronicles", name: "1 Chronicles", chapters: 29, file: "1-Chronicles.json" },
  { id: "2-chronicles", name: "2 Chronicles", chapters: 36, file: "2-Chronicles.json" },
  { id: "ezra", name: "Ezra", chapters: 10, file: "Ezra.json" },
  { id: "nehemiah", name: "Nehemiah", chapters: 13, file: "Nehemiah.json" },
  { id: "esther", name: "Esther", chapters: 10, file: "Esther.json" },
  { id: "job", name: "Job", chapters: 42, file: "Job.json" },
  { id: "psalms", name: "Psalms", chapters: 150, file: "Psalms.json" },
  { id: "proverbs", name: "Proverbs", chapters: 31, file: "Proverbs.json" },
  { id: "ecclesiastes", name: "Ecclesiastes", chapters: 12, file: "Ecclesiastes.json" },
  { id: "song-of-solomon", name: "Song of Solomon", chapters: 8, file: "Song-of-Solomon.json" },
  { id: "isaiah", name: "Isaiah", chapters: 66, file: "Isaiah.json" },
  { id: "jeremiah", name: "Jeremiah", chapters: 52, file: "Jeremiah.json" },
  { id: "lamentations", name: "Lamentations", chapters: 5, file: "Lamentations.json" },
  { id: "ezekiel", name: "Ezekiel", chapters: 48, file: "Ezekiel.json" },
  { id: "daniel", name: "Daniel", chapters: 12, file: "Daniel.json" },
  { id: "hosea", name: "Hosea", chapters: 14, file: "Hosea.json" },
  { id: "joel", name: "Joel", chapters: 3, file: "Joel.json" },
  { id: "amos", name: "Amos", chapters: 9, file: "Amos.json" },
  { id: "obadiah", name: "Obadiah", chapters: 1, file: "Obadiah.json" },
  { id: "jonah", name: "Jonah", chapters: 4, file: "Jonah.json" },
  { id: "micah", name: "Micah", chapters: 7, file: "Micah.json" },
  { id: "nahum", name: "Nahum", chapters: 3, file: "Nahum.json" },
  { id: "habakkuk", name: "Habakkuk", chapters: 3, file: "Habakkuk.json" },
  { id: "zephaniah", name: "Zephaniah", chapters: 3, file: "Zephaniah.json" },
  { id: "haggai", name: "Haggai", chapters: 2, file: "Haggai.json" },
  { id: "zechariah", name: "Zechariah", chapters: 14, file: "Zechariah.json" },
  { id: "malachi", name: "Malachi", chapters: 4, file: "Malachi.json" },

  { id: "matthew", name: "Matthew", chapters: 28, file: "Matthew.json" },
  { id: "mark", name: "Mark", chapters: 16, file: "Mark.json" },
  { id: "luke", name: "Luke", chapters: 24, file: "Luke.json" },
  { id: "john", name: "John", chapters: 21, file: "john.json" },
  { id: "acts", name: "Acts", chapters: 28, file: "Acts.json" },
  { id: "romans", name: "Romans", chapters: 16, file: "Romans.json" },
  { id: "1-corinthians", name: "1 Corinthians", chapters: 16, file: "1-Corinthians.json" },
  { id: "2-corinthians", name: "2 Corinthians", chapters: 13, file: "2-Corinthians.json" },
  { id: "galatians", name: "Galatians", chapters: 6, file: "Galatians.json" },
  { id: "ephesians", name: "Ephesians", chapters: 6, file: "Ephesians.json" },
  { id: "philippians", name: "Philippians", chapters: 4, file: "Philippians.json" },
  { id: "colossians", name: "Colossians", chapters: 4, file: "Colossians.json" },
  { id: "1-thessalonians", name: "1 Thessalonians", chapters: 5, file: "1-Thessalonians.json" },
  { id: "2-thessalonians", name: "2 Thessalonians", chapters: 3, file: "2-Thessalonians.json" },
  { id: "1-timothy", name: "1 Timothy", chapters: 6, file: "1-Timothy.json" },
  { id: "2-timothy", name: "2 Timothy", chapters: 4, file: "2-Timothy.json" },
  { id: "titus", name: "Titus", chapters: 3, file: "Titus.json" },
  { id: "philemon", name: "Philemon", chapters: 1, file: "Philemon.json" },
  { id: "hebrews", name: "Hebrews", chapters: 13, file: "Hebrews.json" },
  { id: "james", name: "James", chapters: 5, file: "James.json" },
  { id: "1-peter", name: "1 Peter", chapters: 5, file: "1-Peter.json" },
  { id: "2-peter", name: "2 Peter", chapters: 3, file: "2-Peter.json" },
  { id: "1-john", name: "1 John", chapters: 5, file: "1-John.json" },
  { id: "2-john", name: "2 John", chapters: 1, file: "2-John.json" },
  { id: "3-john", name: "3 John", chapters: 1, file: "3-John.json" },
  { id: "jude", name: "Jude", chapters: 1, file: "Jude.json" },
  { id: "revelation", name: "Revelation", chapters: 22, file: "Revelation.json" }
];

export function getBookById(id: string) {
  return BOOKS.find(b => b.id === id.toLowerCase());
}
